from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pymysql

connection = pymysql.connect(host = 'localhost',
                            port = 3306,
                            user = 'root',
                            db = 'testEngine_2',
                            autocommit = True)

cursor = connection.cursor()

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 802)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1271, 761))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(350, 30, 581, 61))
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(70, 430, 361, 91))
        self.pushButton.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 430, 361, 91))
        self.pushButton_2.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(110, 250, 251, 71))
        self.comboBox.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(840, 240, 251, 71))
        self.comboBox_2.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.register_frame = QtWidgets.QFrame(self.frame)
        self.register_frame.setGeometry(QtCore.QRect(0, 0, 1261, 751))
        self.register_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.register_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.register_frame.setObjectName("register_frame")
        self.label_2 = QtWidgets.QLabel(self.register_frame)
        self.label_2.setGeometry(QtCore.QRect(410, 60, 381, 71))
        self.label_2.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.register_frame)
        self.label_3.setGeometry(QtCore.QRect(150, 200, 411, 51))
        self.label_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.register_frame)
        self.label_4.setGeometry(QtCore.QRect(150, 300, 411, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.register_frame)
        self.label_5.setGeometry(QtCore.QRect(150, 410, 411, 51))
        self.label_5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.register_frame)
        self.label_6.setGeometry(QtCore.QRect(150, 520, 411, 51))
        self.label_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.register_frame)
        self.lineEdit.setGeometry(QtCore.QRect(590, 190, 451, 61))
        self.lineEdit.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.register_frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(590, 290, 451, 61))
        self.lineEdit_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.register_frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(590, 510, 451, 61))
        self.lineEdit_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.register_frame)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 650, 341, 61))
        self.pushButton_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.register_frame)
        self.comboBox_3.setGeometry(QtCore.QRect(590, 400, 451, 71))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.register_frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1271, 751))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(510, 50, 231, 71))
        self.label_7.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(180, 210, 251, 71))
        self.label_8.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(180, 350, 311, 71))
        self.label_9.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(620, 210, 471, 71))
        self.lineEdit_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(620, 350, 471, 71))
        self.lineEdit_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 530, 351, 81))
        self.pushButton_4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1271, 761))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(500, 20, 331, 91))
        self.label_10.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_4.setGeometry(QtCore.QRect(680, 190, 351, 81))
        self.comboBox_4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(250, 190, 351, 71))
        self.label_11.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 430, 371, 81))
        self.pushButton_5.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1261, 761))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 40, 1231, 81))
        self.lineEdit_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 190, 361, 61))
        self.lineEdit_7.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(650, 190, 361, 61))
        self.lineEdit_8.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(170, 320, 361, 61))
        self.lineEdit_9.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(650, 320, 361, 61))
        self.lineEdit_10.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(430, 460, 361, 61))
        self.lineEdit_11.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 610, 531, 81))
        self.pushButton_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(1020, 630, 211, 51))
        self.pushButton_7.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1271, 771))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(150, 50, 881, 61))
        self.label_12.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(150, 190, 1031, 51))
        self.label_13.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(150, 300, 1031, 51))
        self.label_14.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(160, 400, 1031, 51))
        self.label_15.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setGeometry(QtCore.QRect(510, 570, 431, 81))
        self.pushButton_8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1271, 761))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(30, 140, 1171, 71))
        self.label_16.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton.setGeometry(QtCore.QRect(50, 250, 501, 61))
        self.radioButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 350, 501, 61))
        self.radioButton_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 450, 501, 61))
        self.radioButton_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 540, 501, 61))
        self.radioButton_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setGeometry(QtCore.QRect(700, 640, 291, 71))
        self.pushButton_9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(810, 30, 221, 51))
        self.label_17.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_6)
        self.lcdNumber.setGeometry(QtCore.QRect(1050, 30, 141, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1271, 751))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(100, 110, 451, 71))
        self.label_18.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(610, 130, 111, 41))
        self.label_19.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_7)
        self.label_20.setGeometry(QtCore.QRect(110, 260, 451, 71))
        self.label_20.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_7)
        self.label_21.setGeometry(QtCore.QRect(120, 410, 451, 71))
        self.label_21.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(610, 280, 111, 41))
        self.label_22.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(610, 430, 111, 41))
        self.label_23.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1265, 31))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        self.menuRegister = QtWidgets.QMenu(self.menubar)
        self.menuRegister.setObjectName("menuRegister")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())
        self.menubar.addAction(self.menuRegister.menuAction())

        # self.frame.hide()
        self.register_frame.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Test Engine"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_2.setText(_translate("MainWindow", "Register"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Teacher"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Student"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Teacher"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Student"))
        self.label_2.setText(_translate("MainWindow", "Registration Form"))
        self.label_3.setText(_translate("MainWindow", "Enter ID"))
        self.label_4.setText(_translate("MainWindow", "Enter Name"))
        self.label_5.setText(_translate("MainWindow", "Enter Department"))
        self.label_6.setText(_translate("MainWindow", "Enter Password"))
        self.pushButton_3.setText(_translate("MainWindow", "Register"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "CS/IT"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "EC"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "ME"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "EE"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "EEE"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Civil"))
        self.label_7.setText(_translate("MainWindow", "Login Form"))
        self.label_8.setText(_translate("MainWindow", "Enter ID"))
        self.label_9.setText(_translate("MainWindow", "Enter Password"))
        self.pushButton_4.setText(_translate("MainWindow", "Login"))
        self.label_10.setText(_translate("MainWindow", "Welcome User"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "python"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "c/c++"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "java"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "php"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "android"))
        self.label_11.setText(_translate("MainWindow", "Select Subject"))
        self.pushButton_5.setText(_translate("MainWindow", "Submit"))
        self.lineEdit_6.setText(_translate("MainWindow", "Enter Question..."))
        self.lineEdit_7.setText(_translate("MainWindow", "Option_1"))
        self.lineEdit_8.setText(_translate("MainWindow", "Option_2"))
        self.lineEdit_9.setText(_translate("MainWindow", "Option_3"))
        self.lineEdit_10.setText(_translate("MainWindow", "Option_4"))
        self.lineEdit_11.setText(_translate("MainWindow", "Answer"))
        self.pushButton_6.setText(_translate("MainWindow", "Insert Question"))
        self.pushButton_7.setText(_translate("MainWindow", "Exit"))
        self.label_12.setText(_translate("MainWindow", "Instructions for test"))
        self.label_13.setText(_translate("MainWindow", "Test will be of 30 minutes."))
        self.label_14.setText(_translate("MainWindow", "Test will be of 30 minutes."))
        self.label_15.setText(_translate("MainWindow", "Test will be of 30 minutes."))
        self.pushButton_8.setText(_translate("MainWindow", "Start Test"))
        self.label_16.setText(_translate("MainWindow", "Question..."))
        self.radioButton.setText(_translate("MainWindow", "Option_1"))
        self.radioButton_2.setText(_translate("MainWindow", "Option_2"))
        self.radioButton_3.setText(_translate("MainWindow", "Option_3"))
        self.radioButton_4.setText(_translate("MainWindow", "Option_4"))
        self.pushButton_9.setText(_translate("MainWindow", "Next"))
        self.label_17.setText(_translate("MainWindow", "Time Left : "))
        self.label_18.setText(_translate("MainWindow", "Your Score : "))
        self.label_19.setText(_translate("MainWindow", "00"))
        self.label_20.setText(_translate("MainWindow", "Total Questions : "))
        self.label_21.setText(_translate("MainWindow", "Attempted : "))
        self.label_22.setText(_translate("MainWindow", "00"))
        self.label_23.setText(_translate("MainWindow", "00"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuLogin.setTitle(_translate("MainWindow", "Login"))
        self.menuRegister.setTitle(_translate("MainWindow", "Register"))

        self.pushButton.clicked.connect(self.showLogin)
        self.pushButton_2.clicked.connect(self.showRegister)
        self.pushButton_3.clicked.connect(self.registerUser)
        self.pushButton_4.clicked.connect(self.loginUser)
        self.pushButton_5.clicked.connect(self.checkLogin)
        self.pushButton_6.clicked.connect(self.insertQuestion)

    def showRegister(self):
        self.register_frame.show()
        self.frame_2.hide()
        # self.registerUser()

    def showLogin(self):
        self.register_frame.show()
        self.frame_2.show()
        self.frame_3.hide()
        # self.loginUser()

    def registerUser(self):
        try:
            user = self.comboBox_2.currentText()
            # print(user)
            user_id = self.lineEdit.text()
            user_name = self.lineEdit_2.text()
            user_course = self.comboBox_3.currentText()
            user_pwd = self.lineEdit_4.text()

            if user == 'Student':
                query = 'INSERT INTO students VALUES (%s, %s, %s, %s)'
            else:
                query = 'INSERT INTO teachers VALUES (%s, %s, %s, %s)'

            cursor.execute(query, (user_id, user_name, user_course, user_pwd))
            QMessageBox.about(self,"Success","Data Inserted Successfully...")

        except BaseException as ex:
            print(ex)

    def loginUser(self):
        try:
            user = self.comboBox.currentText()
            # print(user)
            user_id = self.lineEdit_3.text()
            user_pwd = self.lineEdit_5.text()

            if user == 'Student':
                query = 'SELECT * FROM students WHERE s_id = %s AND s_pwd = %s'
            else:
                query = 'SELECT * FROM teachers WHERE t_id = %s AND t_pwd = %s'

            cursor.execute(query, (user_id, user_pwd))

            print("Login Success")
            self.loginSuccess()

        except BaseException as ex:
            print(ex)

    def loginSuccess(self):
        self.frame_3.show()
        self.frame_4.hide()

    def checkLogin(self):
        user = self.comboBox.currentText()
        # print(user)
        if user == "Student":
            self.studentFrame()
        else:
            self.teacherFrame()

    def teacherFrame(self):
        self.frame_4.show()
        self.frame_5.hide()

        self.lineEdit_6.setText("")
        self.lineEdit_7.setText("")
        self.lineEdit_8.setText("")
        self.lineEdit_9.setText("")
        self.lineEdit_10.setText("")
        self.lineEdit_11.setText("")

    def studentFrame(self):
        self.frame_4.show()
        self.frame_6.hide()

    def insertQuestion(self):
        try:
            ques = self.lineEdit_6.text()
            opt_1 = self.lineEdit_7.text()
            opt_2 = self.lineEdit_8.text()
            opt_3 = self.lineEdit_9.text()
            opt_4 = self.lineEdit_10.text()
            ans = self.lineEdit_11.text()
            sub = self.comboBox_4.currentText()

            query = "INSERT INTO questions VALUES (%s, %s, %s, %s, %s, %s, %s)"
            cursor.execute(query, (ques, opt_1, opt_2, opt_3, opt_4, ans, sub))
            QMessageBox.about(self, "Inserted", "Question Inserted")

            self.teacherFrame()
        except BaseException as ex:
            print(ex)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

